
from pyrogram import filters, Client
from pyrogram.types import Message
from pyrogram.enums import ParseMode 
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton , CallbackQuery , Message
import os
import asyncio
import random



questions = [
        {
            "question": "What is the process by which sperms are produced called?",
            "options": ["A. Ovulation", "B. Spermatogenesis", "C. Fertilization", "D. Meiosis"],
            "correct_option": "B",
            "explanation": "Spermatogenesis is the process of sperm cell production. It occurs in the seminiferous tubules of the testes and involves a series of cell divisions and differentiations to form mature sperm cells."
        },
        {
            "question": "Which protein is responsible for the sliding of actin and myosin filaments during muscle contraction?",
            "options": ["A. Troponin", "B. Myosin kinase", "C. Actinin", "D. Tropomyosin"],
            "correct_option": "D",
            "explanation": "Tropomyosin is a protein that covers the active sites on actin during muscle relaxation. During muscle contraction, it moves aside to expose the binding sites for myosin, leading to filament sliding."
        },
        {
            "question": "The contraction of muscle fibers is triggered by the release of which ion from the sarcoplasmic reticulum?",
            "options": ["A. Sodium", "B. Calcium", "C. Potassium", "D. Chloride"],
            "correct_option": "B",
            "explanation": "The release of calcium ions from the sarcoplasmic reticulum into the cytoplasm triggers the interaction between actin and myosin, leading to muscle contraction."
        },
        {
            "question": "Which connective tissue surrounds a bundle of muscle fibers?",
            "options": ["A. Endomysium", "B. Epimysium", "C. Perimysium", "D. Fascia"],
            "correct_option": "C",
            "explanation": "Perimysium is the connective tissue that surrounds a bundle of muscle fibers. It provides structural support and helps in the transmission of force generated during muscle contraction."
        },
        {
            "question": "Which hormone is responsible for the growth and development of bones?",
            "options": ["A. Thyroxine", "B. Estrogen", "C. Insulin", "D. Growth hormone"],
            "correct_option": "D",
            "explanation": "Growth hormone, also known as somatotropin, stimulates the growth and development of bones, cartilage, and tissues by promoting cell division and protein synthesis."
        },
        {
            "question": "Which type of joint allows movement in many directions and is found in the shoulder?",
            "options": ["A. Hinge joint", "B. Ball-and-socket joint", "C. Pivot joint", "D. Gliding joint"],
            "correct_option": "B",
            "explanation": "A ball-and-socket joint allows movement in multiple directions. The shoulder joint is an example of a ball-and-socket joint, providing a wide range of movement."
        },
        {
            "question": "In a sarcomere, which protein forms the thin filaments?",
            "options": ["A. Myosin", "B. Troponin", "C. Tropomyosin", "D. Actin"],
            "correct_option": "D",
            "explanation": "Actin is the protein that forms the thin filaments in a sarcomere. It interacts with myosin during muscle contraction, leading to the sliding of filaments."
        },
        {
            "question": "Which enzyme converts ATP to ADP and inorganic phosphate during muscle contraction?",
            "options": ["A. Myosin kinase", "B. Creatine kinase", "C. ATP synthase", "D. ATPase"],
            "correct_option": "D",
            "explanation": "ATPase is the enzyme responsible for breaking down ATP into ADP and inorganic phosphate, releasing energy that powers muscle contraction."
        },
        {
            "question": "Which structure connects muscle to bone?",
            "options": ["A. Ligament", "B. Tendon", "C. Cartilage", "D. Synovium"],
            "correct_option": "B",
            "explanation": "Tendons are tough connective tissues that attach muscle to bone. They transmit the force generated by muscle contraction to the skeletal system, allowing movement."
        },
        {
            "question": "What is the basic functional unit of muscle contraction called?",
            "options": ["A. Sarcomere", "B. Myofibril", "C. Sarcolemma", "D. Sarcoplasm"],
            "correct_option": "A",
            "explanation": "A sarcomere is the basic structural and functional unit of muscle contraction. It consists of overlapping actin and myosin filaments."
        },
        {
            "question": "Which disorder is characterized by the progressive weakening and loss of muscle tissue?",
            "options": ["A. Osteoporosis", "B. Muscular dystrophy", "C. Arthritis", "D. Gout"],
            "correct_option": "B",
            "explanation": "Muscular dystrophy is a group of genetic disorders that lead to the progressive degeneration and weakening of muscle tissue, resulting in mobility and functional limitations."
        },
        {
            "question": "Which type of muscle is responsible for involuntary contractions of the digestive tract?",
            "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
            "correct_option": "B",
            "explanation": "Smooth muscle is responsible for involuntary movements, such as the contractions of the digestive tract and blood vessels. It lacks striations and is controlled by the autonomic nervous system."
        },
        {
            "question": "Which neurotransmitter is released at the neuromuscular junction to stimulate muscle contraction?",
            "options": ["A. Serotonin", "B. Dopamine", "C. Acetylcholine", "D. Norepinephrine"],
            "correct_option": "C",
            "explanation": "Acetylcholine is the neurotransmitter released at the neuromuscular junction. It binds to receptors on the muscle cell membrane, leading to muscle contraction."
        },
        {
            "question": "Which component of the skeletal system is primarily responsible for producing blood cells?",
            "options": ["A. Bones", "B. Cartilage", "C. Bone marrow", "D. Ligaments"],
            "correct_option": "C",
            "explanation": "Bone marrow, found within certain bones, is responsible for the production of blood cells through a process called hematopoiesis."
        },
       {
                "question": "Which protein provides elasticity and extensibility to muscle fibers?",
                "options": ["A. Actin", "B. Myosin", "C. Collagen", "D. Tropomyosin"],
                "correct_option": "C",
                "explanation": "Collagen is a fibrous protein that provides elasticity and extensibility to muscle fibers and connective tissues. It contributes to the strength and flexibility of muscles."
      },
            {
                "question": "What is the functional unit of contraction in a muscle fiber?",
                "options": ["A. Sarcomere", "B. Myofibril", "C. Endomysium", "D. Perimysium"],
                "correct_option": "A",
                "explanation": "The sarcomere is the functional unit of contraction in a muscle fiber. It is the region between two Z-lines and contains overlapping actin and myosin filaments."
            },
            {
                "question": "Which part of the brain is responsible for coordinating muscle movements and maintaining posture?",
                "options": ["A. Cerebellum", "B. Medulla oblongata", "C. Thalamus", "D. Hypothalamus"],
                "correct_option": "A",
                "explanation": "The cerebellum is responsible for coordinating muscle movements, maintaining posture, and ensuring smooth and balanced motor functions. It plays a crucial role in locomotion."
            },
            {
                "question": "Which type of muscle tissue is striated and under involuntary control?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "C",
                "explanation": "Cardiac muscle tissue is striated and found in the heart. It contracts rhythmically to pump blood and is under involuntary control."
            },
            {
                "question": "What is the main function of synovial fluid in a synovial joint?",
                "options": ["A. Lubrication", "B. Providing blood supply", "C. Transmitting nerve impulses", "D. Generating ATP"],
                "correct_option": "A",
                "explanation": "Synovial fluid lubricates the surfaces of a synovial joint, reducing friction and facilitating smooth movement between the bones."
            },
            {
                "question": "Which type of joint is found between the skull bones and allows minimal movement?",
                "options": ["A. Hinge joint", "B. Pivot joint", "C. Suture joint", "D. Ball-and-socket joint"],
                "correct_option": "C",
                "explanation": "Suture joints are found between the flat bones of the skull. They allow minimal movement and are primarily responsible for holding the skull bones together."
            },
            {
                "question": "Which hormone is responsible for the regulation of calcium levels in the blood and bones?",
                "options": ["A. Thyroxine", "B. Insulin", "C. Parathyroid hormone", "D. Adrenaline"],
                "correct_option": "C",
                "explanation": "Parathyroid hormone (PTH) is responsible for regulating calcium levels in the blood and bones. It increases calcium release from bones and enhances calcium absorption in the intestines."
            },
            {
                "question": "Which type of muscle tissue is found in the walls of hollow organs and blood vessels?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "B",
                "explanation": "Smooth muscle tissue is found in the walls of hollow organs (like the digestive tract) and blood vessels. It contracts involuntarily to facilitate functions such as peristalsis and vasoconstriction."
            },
            {
                "question": "Which bone in the human body is commonly referred to as the collarbone?",
                "options": ["A. Radius", "B. Ulna", "C. Clavicle", "D. Scapula"],
                "correct_option": "C",
                "explanation": "The clavicle, commonly known as the collarbone, is a long bone that connects the sternum to the scapula. It helps in stabilizing the shoulder joint and provides attachment for muscles."
            },
            {
                "question": "What is the role of ligaments in the skeletal system?",
                "options": ["A. Attaching muscles to bones", "B. Connecting bone to bone", "C. Providing cushioning", "D. Producing red blood cells"],
                "correct_option": "B",
                "explanation": "Ligaments are fibrous connective tissues that connect bone to bone. They provide stability to joints and limit excessive movements, preventing dislocations."
            },
                       {
                "question": "Which protein provides elasticity and extensibility to muscle fibers?",
                "options": ["A. Actin", "B. Myosin", "C. Collagen", "D. Tropomyosin"],
                "correct_option": "C",
                "explanation": "Collagen is a fibrous protein that provides elasticity and extensibility to muscle fibers and connective tissues. It contributes to the strength and flexibility of muscles."
            },
            {
                "question": "What is the functional unit of contraction in a muscle fiber?",
                "options": ["A. Sarcomere", "B. Myofibril", "C. Endomysium", "D. Perimysium"],
                "correct_option": "A",
                "explanation": "The sarcomere is the functional unit of contraction in a muscle fiber. It is the region between two Z-lines and contains overlapping actin and myosin filaments."
            },
            {
                "question": "Which part of the brain is responsible for coordinating muscle movements and maintaining posture?",
                "options": ["A. Cerebellum", "B. Medulla oblongata", "C. Thalamus", "D. Hypothalamus"],
                "correct_option": "A",
                "explanation": "The cerebellum is responsible for coordinating muscle movements, maintaining posture, and ensuring smooth and balanced motor functions. It plays a crucial role in locomotion."
            },
            {
                "question": "Which type of muscle tissue is striated and under involuntary control?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "C",
                "explanation": "Cardiac muscle tissue is striated and found in the heart. It contracts rhythmically to pump blood and is under involuntary control."
            },
            {
                "question": "What is the main function of synovial fluid in a synovial joint?",
                "options": ["A. Lubrication", "B. Providing blood supply", "C. Transmitting nerve impulses", "D. Generating ATP"],
                "correct_option": "A",
                "explanation": "Synovial fluid lubricates the surfaces of a synovial joint, reducing friction and facilitating smooth movement between the bones."
            },
            {
                "question": "Which type of joint is found between the skull bones and allows minimal movement?",
                "options": ["A. Hinge joint", "B. Pivot joint", "C. Suture joint", "D. Ball-and-socket joint"],
                "correct_option": "C",
                "explanation": "Suture joints are found between the flat bones of the skull. They allow minimal movement and are primarily responsible for holding the skull bones together."
            },
            {
                "question": "Which hormone is responsible for the regulation of calcium levels in the blood and bones?",
                "options": ["A. Thyroxine", "B. Insulin", "C. Parathyroid hormone", "D. Adrenaline"],
                "correct_option": "C",
                "explanation": "Parathyroid hormone (PTH) is responsible for regulating calcium levels in the blood and bones. It increases calcium release from bones and enhances calcium absorption in the intestines."
            },
            {
                "question": "Which type of muscle tissue is found in the walls of hollow organs and blood vessels?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "B",
                "explanation": "Smooth muscle tissue is found in the walls of hollow organs (like the digestive tract) and blood vessels. It contracts involuntarily to facilitate functions such as peristalsis and vasoconstriction."
            },
            {
                "question": "Which bone in the human body is commonly referred to as the collarbone?",
                "options": ["A. Radius", "B. Ulna", "C. Clavicle", "D. Scapula"],
                "correct_option": "C",
                "explanation": "The clavicle, commonly known as the collarbone, is a long bone that connects the sternum to the scapula. It helps in stabilizing the shoulder joint and provides attachment for muscles."
            },
            {
                "question": "What is the role of ligaments in the skeletal system?",
                "options": ["A. Attaching muscles to bones", "B. Connecting bone to bone", "C. Providing cushioning", "D. Producing red blood cells"],
                "correct_option": "B",
                "explanation": "Ligaments are fibrous connective tissues that connect bone to bone. They provide stability to joints and limit excessive movements, preventing dislocations."
            },
            {
                "question": "Which type of joint allows the movement of rotation?",
                "options": ["A. Hinge joint", "B. Pivot joint", "C. Ball-and-socket joint", "D. Gliding joint"],
                "correct_option": "B",
                "explanation": "A pivot joint allows rotational movement. An example is the joint between the atlas and axis vertebrae, allowing the head to turn from side to side."
            },
            {
                "question": "Which mineral is essential for muscle contraction and is stored in the sarcoplasmic reticulum?",
                "options": ["A. Sodium", "B. Potassium", "C. Magnesium", "D. Calcium"],
                "correct_option": "D",
                "explanation": "Calcium is essential for muscle contraction. It is stored in the sarcoplasmic reticulum and is released during excitation-contraction coupling to initiate muscle contraction."
            },
            {
                "question": "Which disorder is characterized by inflammation of the joints, leading to pain and stiffness?",
                "options": ["A. Osteoporosis", "B. Muscular dystrophy", "C. Arthritis", "D. Gout"],
                "correct_option": "C",
                "explanation": "Arthritis is a condition where joints become inflamed, leading to pain, swelling, and stiffness. Osteoarthritis and rheumatoid arthritis are common types of arthritis."
            },
            {
                "question": "Which type of muscle tissue has intercalated discs?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "C",
                "explanation": "Cardiac muscle tissue has intercalated discs, which contain gap junctions that allow rapid transmission of electrical signals, ensuring synchronized contractions of the heart."
            },
            {
                "question": "Which component of the skeletal system protects the delicate organs in the cranial cavity?",
                "options": ["A. Vertebrae", "B. Ribs", "C. Sternum", "D. Skull bones"],
                "correct_option": "D",
                "explanation": "Skull bones protect the brain and sensory organs in the cranial cavity. The cranium and facial bones provide structural support and safeguard vital organs."
            },
            {
                "question": "Which type of muscle contraction causes the muscle to shorten while generating tension?",
                "options": ["A. Isometric contraction", "B. Concentric contraction", "C. Eccentric contraction", "D. Static contraction"],
                "correct_option": "B",
                "explanation": "Concentric contraction occurs when the muscle shortens while generating tension. This type of contraction is responsible for movement against gravity or resistance."
            },
            {
                "question": "Which hormone stimulates the growth of long bones during childhood and adolescence?",
                "options": ["A. Insulin", "B. Thyroxine", "C. Growth hormone", "D. Estrogen"],
                "correct_option": "C",
                "explanation": "Growth hormone stimulates the growth of long bones during childhood and adolescence. It promotes cell division, protein synthesis, and overall body growth."
            },
            {
                "question": "Which of the following structures stores and releases acetylcholine in a neuromuscular junction?",
                "options": ["A. Axon terminal", "B. Dendrite", "C. Synaptic cleft", "D. Myelin sheath"],
                "correct_option": "A",
                "explanation": "The axon terminal of a motor neuron stores and releases acetylcholine into the synaptic cleft, where it binds to receptors on the muscle cell membrane, leading to muscle contraction."
            },
            {
                "question": "Which connective tissue covers individual muscle fibers?",
                "options": ["A. Endomysium", "B. Epimysium", "C. Perimysium", "D. Tendon"],
                "correct_option": "A",
                "explanation": "Endomysium is the connective tissue that covers individual muscle fibers. It provides insulation and separates muscle fibers from each other within a muscle."
            },
            {
                "question": "Which type of joint allows only bending and straightening movements?",
                "options": ["A. Hinge joint", "B. Pivot joint", "C. Ball-and-socket joint", "D. Gliding joint"],
                "correct_option": "A",
                "explanation": "A hinge joint allows movement in only one plane, resembling the opening and closing of a door. The elbow and knee joints are examples of hinge joints."
            },
            {
                "question": "What is the main function of the synovial membrane in a synovial joint?",
                "options": ["A. Producing synovial fluid", "B. Providing blood supply", "C. Transmitting nerve impulses", "D. Regulating hormone production"],
                "correct_option": "A",
                "explanation": "The synovial membrane lines the inner surface of the joint capsule and produces synovial fluid, which lubricates the joint and nourishes the articular cartilage."
            },
            {
                "question": "Which bone is also known as the shoulder blade?",
                "options": ["A. Radius", "B. Ulna", "C. Clavicle", "D. Scapula"],
                "correct_option": "D",
                "explanation": "The scapula, commonly known as the shoulder blade, is a flat, triangular bone located on the upper back. It provides attachment sites for several muscles involved in shoulder movement."
            },
            {
                "question": "Which type of muscle contraction occurs when the muscle lengthens while generating tension?",
                "options": ["A. Isometric contraction", "B. Concentric contraction", "C. Eccentric contraction", "D. Static contraction"],
                "correct_option": "C",
                "explanation": "Eccentric contraction occurs when the muscle lengthens while generating tension. This type of contraction is involved in controlling movements and resisting external forces."
            },
            {
                "question": "Which hormone is responsible for the maintenance of blood calcium levels by promoting calcium uptake in bones?",
                "options": ["A. Parathyroid hormone", "B. Insulin", "C. Thyroxine", "D. Growth hormone"],
                "correct_option": "A",
                "explanation": "Parathyroid hormone (PTH) maintains blood calcium levels by promoting calcium release from bones and increasing calcium reabsorption by the kidneys."
            },
            {
                "question": "Which structure connects bone to muscle?",
                "options": ["A. Ligament", "B. Tendon", "C. Cartilage", "D. Synovium"],
                "correct_option": "B",
                "explanation": "Tendons are fibrous connective tissues that attach muscles to bones. They transmit the force generated during muscle contraction to the skeletal system, allowing movement."
            },
            {
                "question": "Which type of muscle tissue is found in the heart?",
                "options": ["A. Skeletal muscle", "B. Smooth muscle", "C. Cardiac muscle", "D. Striated muscle"],
                "correct_option": "C",
                "explanation": "Cardiac muscle tissue is found in the heart. It is responsible for pumping blood throughout the circulatory system and is under involuntary control."
            },
            {
                "question": "Which component of the skeletal system protects the spinal cord?",
                "options": ["A. Vertebrae", "B. Ribs", "C. Sternum", "D. Skull bones"],
                "correct_option": "A",
                "explanation": "Vertebrae are the bones that form the vertebral column, protecting the spinal cord. They provide structural support and flexibility to the back."
            }

]



current_question_index = 0

@Client.on_message(filters.command("skeletal"))
async def quiz(_, message):
    global current_question_index
    current_question_index = 0
    await show_question(message)

async def show_question(message):
    question_data = questions[current_question_index]
    question_text = question_data["question"]
    options = question_data["options"]

    keyboard = []
    for option in options:
        button = InlineKeyboardButton(text=option, callback_data=f"answer:{option}")
        keyboard.append([button])

    navigation_buttons = []
    if current_question_index > 0:
        navigation_buttons.append(InlineKeyboardButton("Previous", callback_data="previous"))
    if current_question_index < len(questions) - 1:
        navigation_buttons.append(InlineKeyboardButton("Next", callback_data="next"))

    keyboard.append(navigation_buttons)
    
    reply_markup = InlineKeyboardMarkup(keyboard)
    await message.reply_text(question_text, reply_markup=reply_markup)

@Client.on_callback_query(filters.regex(r"^answer:"))
async def answer(_, query: CallbackQuery):
    selected_option = query.data.split(":")[1]
    question = next(q for q in questions if selected_option in q["options"])

    if question:
        if selected_option == question["correct_option"]:
            response_text = "Correct! Well done."
        else:
            response_text = f"The correct answer is {question['correct_option']}."

        await query.answer(response_text)
        await query.message.reply_text(
            f"Question: {question['explanation']}\n\nCorrect Answer: {question['correct_option']}"
        )
    else:
        query.answer("Invalid selection. Please try again.")

@Client.on_callback_query(filters.regex(r"^(previous|next)$"))
async def navigation_button(_, query: CallbackQuery):
    global current_question_index

    if query.data == "previous":
        current_question_index = max(0, current_question_index - 1)
    elif query.data == "next":
        current_question_index = min(len(questions) - 1, current_question_index + 1)

    await query.answer()

    # Re-send the question with the updated index
    await show_question(query.message)
